irb(main):043:0> check = ListStatusChangeService.new.call
  SalesOrder Load (0.4ms)  SELECT "sales_orders".* FROM "sales_orders" WHERE (DATE(last_checked_date) > DATE(previous_last_checked_date))
=> "<order><id>3686453</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686451</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686449</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686448</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686426</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686425</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686424</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686422</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686413</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686412</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order>"



irb(main):044:0> check = GetOrderUpdatesService.new.call
  SalesOrder Load (0.5ms)  SELECT "sales_orders".* FROM "sales_orders" WHERE "sales_orders"."order_status" IN ($1, $2, $3, $4)  [["order_status", 0], ["order_status", 1], ["order_status", 2], ["order_status", 3]]
  SalesOrder Load (0.8ms)  SELECT "sales_orders".* FROM "sales_orders" WHERE (DATE(last_checked_date) > DATE(previous_last_checked_date))
Orders to be updated in BJ Backoffice: <order><id>3686453</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686451</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686449</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686448</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686426</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686425</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686424</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686422</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686413</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order><order><id>3686412</id><status>completed</status><volumeDelivered>0.0</volumeDelivered></order>

